version: '3'

services:
    app:
        container_name: app
        
        build:
            context: ..
            dockerfile: docker/Dockerfile

        ports:
            - "8000:8000"
        restart: unless-stopped
